#!/bin/bash

echo "🎯 Quick Start Guide for Taskito"
echo ""
echo "1. Add Taskito to your MCP client config:"
echo "   Use the config in: mcp-config-example.json"
echo ""
echo "2. Navigate to any project directory:"
echo "   cd my-awesome-project"
echo ""
echo "3. Example commands to try:"
echo ""
echo "   📝 Initialize a project:"
echo "   'Initialize project \"My App\" using PRD file \"./example-prd.md\"'"
echo ""
echo "   ✨ Create tasks:"
echo "   'Create a task \"Setup Database\" with description \"Configure PostgreSQL\" with size \"m\"'"
echo "   'Create a task \"User Auth\" that depends on task-1 with size \"l\" and priority \"high\"'"
echo ""
echo "   📋 Manage tasks:"
echo "   'List all tasks'"
echo "   'Update task-1 status to \"in-progress\"'"
echo "   'Show me available tasks I can start'"
echo ""
echo "   📊 Track progress:"
echo "   'Get project overview'"
echo "   'Check dependencies for task-2'"
echo ""
echo "   🧹 Maintain project:"
echo "   'Archive completed tasks older than 30 days'"
echo "   'Clean project'"
echo ""
echo "🎯 Task Sizing Guide:"
echo "   XS 🟢 < 1h     S 🔵 1-4h     M 🟡 4-8h     L 🟠 1-2d     XL 🔴 2+d"
echo ""
echo "📁 Project Structure:"
echo "   your-project/"
echo "   ├── taskito/"
echo "   │   └── tasks.json    # Your tasks stored here"
echo "   └── src/              # Your project files"
echo ""
echo "For detailed docs, see README.md"